# :----------------------------------------------------------------------- INFO
# :[ael-architect/project.toml]
# :author        : fantomH
# :created       : 2024-08-29 08:58:35 UTC
# :updated       : 2024-08-29 08:58:41 UTC
# :description   : "Setup script for ael-architect"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ael-architect"
version = "1.0.0"
description = "AlterEGO Linux configuration and setup utility."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Pascal Malouin", email = "pascal.malouin@gmail.com" }
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux"
]
dependencies = [
    "python-magic"
]

[project.urls]
Homepage = "https://github.com/alterEGO-Linux/ael-architect"

[tool.setuptools]
packages = { find = { include = ["*"] } }
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
"ael_architect" = ["data/*"]

[project.scripts]
ael-architect = "ael_architect:main"
